image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            script:
              - IMAGE_NAME=$BITBUCKET_REPO_SLUG
              - docker build . --file Dockerfile --tag ${IMAGE_NAME}
            services:
              - docker
            caches:
              - docker
        - step:
            name: Lint the Dockerfile
            image: hadolint/hadolint:latest-debian
            script:
              - hadolint Dockerfile
        - step:
            name: TestRunApp
            script:
              - APP_ENV=local
              - IMAGE_NAME=$BITBUCKET_REPO_SLUG
              - docker build . --file Dockerfile --tag ${IMAGE_NAME}
              - docker container  run --env APP_ENV=${APP_ENV} -p8020:8080 ${IMAGE_NAME}
              - find . -name '*.php' -exec php -l {} \;
            services:
              - docker
              - database
            caches:
              - docker
  branches:
    master:
      - parallel:
          - step:
              name: Build and Test
              script:
                - IMAGE_NAME=$BITBUCKET_REPO_SLUG
                - APP_ENV=local
                - docker build . --file Dockerfile --tag ${IMAGE_NAME}
              services:
                - docker
              caches:
                - docker
          - step:
              name: Lint the Dockerfile
              image: hadolint/hadolint:latest-debian
              script:
                - hadolint Dockerfile
definitions:
  services:
    database:
      image: mysql:5.7
      variables:
        MYSQL_DATABASE: 'ccfound'
        MYSQL_ROOT_PASSWORD: '4567'