<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIN2jZvA\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIN2jZvA/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/ContainerIN2jZvA.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\ContainerIN2jZvA\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \ContainerIN2jZvA\App_KernelLocalDebugContainer([
    'container.build_hash' => 'IN2jZvA',
    'container.build_id' => '394cc395',
    'container.build_time' => 1628111837,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIN2jZvA');
