<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPRrIF1s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPRrIF1s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPRrIF1s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPRrIF1s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPRrIF1s\App_KernelDevDebugContainer([
    'container.build_hash' => 'PRrIF1s',
    'container.build_id' => 'da775f5e',
    'container.build_time' => 1628111736,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPRrIF1s');
